### 高斯消去法

In [1]:
import pandas as pd
import numpy as np

In [43]:
# arr = np.array([[1,2/3,1/3,2],[9/20,1,11/20,2],[2/3,1/3,1,2]])
# arr = np.array([[2,2,2,1],[3,2,4,1/2],[1,3,9,5/2]])
# arr = np.array([[0.0003,3.0000,2.0001],[1.0000,1.0000,1.0000]])
arr = np.array([[-0.002,2,2,0.4],[1,0.78125,0,1.3816],[3.996,5.5625,4,7.4178]])

In [44]:
arr

array([[-2.0000e-03,  2.0000e+00,  2.0000e+00,  4.0000e-01],
       [ 1.0000e+00,  7.8125e-01,  0.0000e+00,  1.3816e+00],
       [ 3.9960e+00,  5.5625e+00,  4.0000e+00,  7.4178e+00]])

### 公式
- $A[i,j:] = A[i,j:] - A[i,i:] * \frac {A[j,i]}{A[i,i]}$ , $j = (i +1,n) $

In [49]:
## 只考虑方程组有唯一解的时候
n = 3
for i in range(n):
    for j in range(i+1,n):
        arr[j,i:] -= arr[i,i:] * (arr[j,i] / arr[i,i])

In [50]:
arr

array([[-2.00000000e-03,  2.00000000e+00,  2.00000000e+00,
         4.00000000e-01],
       [ 0.00000000e+00,  1.00078125e+03,  1.00000000e+03,
         2.01381600e+02],
       [ 0.00000000e+00,  0.00000000e+00,  1.56128025e+00,
         1.40581311e+00]])

In [51]:
#### 进行回代
ans = np.zeros(n) ## 将数据先设置为0，可以巧妙运算
ans[n - 1] = arr[n-1,n] / arr[n-1,n-1]
for i in range(n - 2,-1,-1):
    ans[i] = (arr[i][n] - np.sum(arr[i,:-1] * ans)) / arr[i][i]

In [52]:
ans

array([ 1.9273   , -0.698496 ,  0.9004233])

### 引理5.1
- 约化的主元素$A_{ii} \neq 0(i=1,2,...,n)$的充要条件是矩阵$A$的[顺序主子式](https://baike.baidu.com/item/%E9%A1%BA%E5%BA%8F%E4%B8%BB%E5%AD%90%E5%BC%8F)$D_{i} \neq 0(i=1,2,...,n)。$
- 这里只要$n-1$阶主子式不等于零就可以。如果消元之后最后一个元素为零，而对应的$b$非零，那么方程没有解。

### 时间复杂度
- $N^3$

### 缺陷
- (1)需要计算行列式的值
- (2)如果消元过程中，对角线元素非常小，那么会增加误差。

### Gauss消元解决方法
- 列主元消去法，就是取列元素最大的行和当前处理的行进行交换。
- 优点：数值稳定，缺点:既消元又回代。

### 求解逆矩阵
- $[A I] = [I A^{-1}]$,因为$AA^{-1}=I, A w_{j} = e_{j},w_{j}$为逆矩阵的$j$列，那么将$Ae_{j}$化为$I,w$的时候$w_{j} = w$，同理$A^{-1}$也可以求出。