### LU
- 对一个矩阵进行行变换，相当于左乘一个矩阵。列变换，相当于右乘一个矩阵。
- $A = LU$,其中$L = L_{1} \times L_{2} \times ... \times L_{n}$,其中$L_{i}$为原子下三角矩阵。比如$L_{0} = \begin{bmatrix} 1 & 0 & 0 \\ -3 & 0 & 0 
\\ 4 & 0 &0\end{bmatrix}$
- 原子矩阵的下三角矩阵的逆为除对角线元素外，所有元素取相反数。比如$L_{0}^{-1} = \begin{bmatrix} 1 & 0 & 0 \\ 3 & 0 & 0 
\\ -4 & 0 &0\end{bmatrix} $
- $det(A) = det(U) = u_{11}u_{22} \times ... \times u_{nn}$

- $A = LU$,则$Ax = b$,$LUx=b$,令$Ux = y$,则$Ly=b$,求出$y$后再求出$x$

### 初等置换矩阵
- 例如$\begin{bmatrix} 1 & 0 \\ 0 & 1\end{bmatrix}$的初等置换矩阵为$\begin{bmatrix} 0 & 1\\ 1 & 0\end{bmatrix}$
- 初等置换矩阵的逆等于其本身。

### 列主元消去法
- 在进行$LU$分解的时候加上行变换。
- $L_{1}I_{1,i1}A^{1} = A^{2},\\ L_{k}I_{k,ik}A^{k}=A^{k + 1}$ 其中$I_{k,ik}$为初等置换阵。
- 于是$L_{n-1}I_{n-1,i(n-1)}...L_{2}I_{2,i2}L_{1}I_{1,i1}A = A^{n}=U$
- 以$n=4$为例：$$\begin{split}U = A^{4}   &=L_{3}I_{3,i3}L_{2}I_{2,i2}L_{1}I_{1,i1}A \\ &= L_{3}(I_{3,i3}L_{2}I_{3,i3})(I_{3,i3}I_{2,i2}L_{1}I_{2,i2}I_{3,i3})(I_{3,i3}I_{2,i2}I_{1,i1})A \\ &= \tilde{L_{3}} \tilde{L_{2}} \tilde{L_{1}} P A  \end{split}$$
- 记$L^{-1} = \tilde{L_{3}} \tilde{L_{2}} \tilde{L_{1}}$则$PA = LU$。其中$P$为排列矩阵，$L$为单位下三角矩阵，$U$为上三角矩阵，列主元素高斯消去法相当于先进行一系列行交换后再对$PAX=Pb$应用顺序高斯消去法。

### 直接三角分解法
- 递推求解方程

In [90]:
import numpy as np
arr = np.array([[1,2,1],[-2,-1,-5],[0,-1,6]])
n = 3

In [91]:
L = np.diag(np.ones(n))
R = np.zeros_like(arr)

In [92]:
R[0,:] = arr[0,:]
L[1:,0] = arr[1:,0] / arr[0][0]

In [93]:
for i in range(1,n):
    for j in range(i,n): ### 第i行
        R[i][j] = arr[i][j] - np.sum(L[i,:i] * R[:i,j])
    for k in range(i + 1,n): ## 求第i列 
        L[k][i] = (arr[k][i] - np.sum(L[k,:i] * R[:i,i])) / R[i][i]

In [94]:
L,R

(array([[ 1.        ,  0.        ,  0.        ],
        [-2.        ,  1.        ,  0.        ],
        [ 0.        , -0.33333333,  1.        ]]), array([[ 1,  2,  1],
        [ 0,  3, -3],
        [ 0,  0,  5]]))

### 直接使用原来矩阵

In [95]:
arr = np.array([[1.0,2.0,1.0],[-2.0,-1.0,-5.0],[0.0,-1.0,6.0]]) 
### 注意这里应该使用浮点数，不然的话，当计算出来是浮点数进行赋值的时候，
### 会出现四舍五入的情况
arr[1:,0] = arr[1:,0] / arr[0][0]
arr

array([[ 1.,  2.,  1.],
       [-2., -1., -5.],
       [ 0., -1.,  6.]])

In [96]:
for i in range(1,n):
    for j in range(i,n): ### 第i行
        arr[i][j] = arr[i][j] - np.sum(arr[i,:i] * arr[:i,j])
    for k in range(i + 1,n): ## 求第i列 
        arr[k][i] = (arr[k][i] - np.sum(arr[k,:i] * arr[:i,i])) / arr[i][i]
    

In [97]:
arr

array([[ 1.        ,  2.        ,  1.        ],
       [-2.        ,  3.        , -3.        ],
       [ 0.        , -0.33333333,  5.        ]])