In [103]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
import random
from sklearn import metrics

In [62]:
x = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])

In [63]:
x.mean(axis = 1)

array([0.66666667, 0.66666667, 0.        ])

In [64]:
x.std(axis = 1)

array([1.24721913, 0.94280904, 0.81649658])

In [65]:
scale_x = preprocessing.scale(x)
scale_x

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [66]:
scale_x.mean(axis = 0)

array([0., 0., 0.])

In [67]:
scale_x.std(axis = 0)

array([1., 1., 1.])

In [68]:
frame = pd.DataFrame([[1,2],[2,3]],columns = ['A','B'])
col_A = frame['A']
col_B = frame['B']

In [69]:
frame.drop(['A'],axis = 1) 

B
0  2
1  3

In [70]:
pd.concat([col_A,col_B],axis = 1)

A  B
0  1  2
1  2  3

In [71]:
scaler = preprocessing.StandardScaler().fit(x)

In [72]:
x_tmp = scaler.transform(x)
x_tmp = pd.DataFrame(x_tmp,columns= ['a','b','c'])
x_tmp

a         b         c
0  0.000000 -1.224745  1.336306
1  1.224745  0.000000 -0.267261
2 -1.224745  1.224745 -1.069045

In [73]:
x_tmp_1 = scaler.transform([[-1,0,0]])
x_tmp_1 = pd.DataFrame(x_tmp_1,columns= ['a','b','c'])
x_tmp_1

a    b         c
0 -2.44949  0.0 -0.267261

In [74]:
result = pd.concat([x_tmp,x_tmp_1])
result

a         b         c
0  0.000000 -1.224745  1.336306
1  1.224745  0.000000 -0.267261
2 -1.224745  1.224745 -1.069045
0 -2.449490  0.000000 -0.267261

In [79]:
random.random()

0.3579323531383497

In [93]:
np.random.randint(0,2)

0

In [94]:
samples = [[0., 0., 0.], [0., .5, 0.], [1., 1., .5]]

In [101]:
data = pd.DataFrame([[1,2,3],[4,5,6]],columns = ['a','b','c'])

In [102]:
data[:1] 

a  b  c
0  1  2  3

In [106]:
y = np.array([1, 1, 2, 2])
scores = np.array([0.1, 0.4, 0.35, 0.8])
fpr, tpr, thresholds = metrics.roc_curve(y, scores, pos_label=2)

In [107]:
fpr, tpr, thresholds

(array([0. , 0.5, 0.5, 1. ]),
 array([0.5, 0.5, 1. , 1. ]),
 array([0.8 , 0.4 , 0.35, 0.1 ]))

In [111]:
from sklearn.metrics import precision_recall_curve
y_true = np.array([0, 0, 1, 1])
y_scores = np.array([0.1, 0.4, 0.35, 0.8])
precision, recall, thresholds = precision_recall_curve(y_true, y_scores)

In [112]:
print(precision)
print(recall)
print(thresholds)

[0.66666667 0.5        1.         1.        ]
[1.  0.5 0.5 0. ]
[0.35 0.4  0.8 ]


In [2]:
import pandas as pd
frame = pd.DataFrame([[1,2],[3,4]],columns =['A','B'])

In [5]:
frame.sample(None,0.5)

A  B
1  3  4

In [6]:
frame

A  B
0  1  2
1  3  4