In [124]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
path = '/Users/icdi/Desktop/gpu-test/DCRNN/data/metr-la.h5'
df = pd.read_hdf(path)
df.head()

773869     767541     767542     717447     717446  \
2012-03-01 00:00:00  64.375000  67.625000  67.125000  61.500000  66.875000   
2012-03-01 00:05:00  62.666667  68.555556  65.444444  62.444444  64.444444   
2012-03-01 00:10:00  64.000000  63.750000  60.000000  59.000000  66.500000   
2012-03-01 00:15:00   0.000000   0.000000   0.000000   0.000000   0.000000   
2012-03-01 00:20:00   0.000000   0.000000   0.000000   0.000000   0.000000   

                        717445  773062  767620     737529     717816   ...    \
2012-03-01 00:00:00  68.750000  65.125  67.125  59.625000  62.750000   ...     
2012-03-01 00:05:00  68.111111  65.000  65.000  57.444444  63.333333   ...     
2012-03-01 00:10:00  66.250000  64.500  64.250  63.875000  65.375000   ...     
2012-03-01 00:15:00   0.000000   0.000   0.000   0.000000   0.000000   ...     
2012-03-01 00:20:00   0.000000   0.000   0.000   0.000000   0.000000   ...     

                        772167  769372     774204     769806  717590  \
2012-03-01 00:00:00  45.625000  65.500  64.500000  66.428571  66.875   
2012-03-01 00:05:00  50.666667  69.875  66.666667  58.555556  62.000   
2012-03-01 00:10:00  44.125000  69.000  56.500000  59.250000  68.125   
2012-03-01 00:15:00   0.000000   0.000   0.000000   0.000000   0.000   
2012-03-01 00:20:00   0.000000   0.000   0.000000   0.000000   0.000   

                        717592     717595     772168     718141  769373  
2012-03-01 00:00:00  59.375000  69.000000  59.250000  69.000000  61.875  
2012-03-01 00:05:00  61.111111  64.444444  55.888889  68.444444  62.875  
2012-03-01 00:10:00  62.500000  65.625000  61.375000  69.857143  62.000  
2012-03-01 00:15:00   0.000000   0.000000   0.000000   0.000000   0.000  
2012-03-01 00:20:00   0.000000   0.000000   0.000000   0.000000   0.000  

[5 rows x 207 columns]

In [125]:
df.tail()

773869     767541     767542     717447  717446  \
2012-06-27 23:35:00  65.000000  65.888889  68.555556  61.666667     0.0   
2012-06-27 23:40:00  61.375000  65.625000  66.500000  62.750000     0.0   
2012-06-27 23:45:00  67.000000  59.666667  69.555556  61.000000     0.0   
2012-06-27 23:50:00  66.750000  62.250000  66.000000  59.625000     0.0   
2012-06-27 23:55:00  65.111111  66.888889  66.777778  61.222222     0.0   

                        717445     773062     767620     737529     717816  \
2012-06-27 23:35:00  54.555556  62.444444  63.333333  59.222222  65.333333   
2012-06-27 23:40:00  50.500000  62.000000  67.000000  65.250000  67.125000   
2012-06-27 23:45:00  44.777778  64.222222  63.777778  59.777778  57.666667   
2012-06-27 23:50:00  53.000000  64.285714  64.125000  60.875000  66.250000   
2012-06-27 23:55:00  49.555556  65.777778  65.111111  63.000000  61.666667   

                       ...         772167     769372     774204     769806  \
2012-06-27 23:35:00    ...      52.888889  69.000000  65.111111  55.666667   
2012-06-27 23:40:00    ...      54.000000  69.250000  60.125000  60.500000   
2012-06-27 23:45:00    ...      51.333333  67.888889  64.333333  57.000000   
2012-06-27 23:50:00    ...      51.125000  69.375000  61.625000  60.500000   
2012-06-27 23:55:00    ...      56.000000  67.444444  64.888889  60.888889   

                        717590     717592     717595     772168     718141  \
2012-06-27 23:35:00  66.333333  62.444444  66.777778  64.888889  69.666667   
2012-06-27 23:40:00  67.250000  59.375000  66.000000  61.250000  69.000000   
2012-06-27 23:45:00  66.000000  62.666667  68.666667  63.333333  67.444444   
2012-06-27 23:50:00  65.625000  66.375000  69.500000  63.000000  67.875000   
2012-06-27 23:55:00  64.222222  66.444444  68.444444  63.555556  68.666667   

                        769373  
2012-06-27 23:35:00  62.333333  
2012-06-27 23:40:00  62.000000  
2012-06-27 23:45:00  61.222222  
2012-06-27 23:50:00  63.500000  
2012-06-27 23:55:00  61.777778  

[5 rows x 207 columns]

In [126]:
df = df.head(1000)

In [127]:
np.concatenate((np.arange(-11, 1, 1),))

array([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [128]:
x_offsets = np.sort(
        # np.concatenate(([-week_size + 1, -day_size + 1], np.arange(-11, 1, 1)))
        np.concatenate((np.arange(-11, 1, 1),))
    )

In [129]:
# x_offsets
y_offsets = np.array(range(1,13))

In [146]:
def generate_graph_seq2seq_io_data(
        df, x_offsets, y_offsets, add_time_in_day=True, add_day_in_week=False, scaler=None
):
    """
    Generate samples from
    :param df:
    :param x_offsets:
    :param y_offsets:
    :param add_time_in_day:
    :param add_day_in_week:
    :param scaler:
    :return:
    # x: (epoch_size, input_length, num_nodes, input_dim)
    # y: (epoch_size, output_length, num_nodes, output_dim)
    """

    num_samples, num_nodes = df.shape
    data = np.expand_dims(df.values, axis=-1)
    data_list = [data]
#     
    if add_time_in_day:
        time_ind = (df.index.values - df.index.values.astype("datetime64[D]")) / np.timedelta64(1, "D")
        time_in_day = np.tile(time_ind, [1, num_nodes, 1]).transpose((2, 1, 0))
        data_list.append(time_in_day)
        
    if add_day_in_week:
        day_in_week = np.zeros(shape=(num_samples, num_nodes, 7))
        day_in_week[np.arange(num_samples), :, df.index.dayofweek] = 1
        data_list.append(day_in_week)
#     print('shape',np.array(data_list).shape)
    data = np.concatenate(data_list, axis=-1)
    # epoch_len = num_samples + min(x_offsets) - max(y_offsets)
    x, y = [], []
    # t is the index of the last observation.
    min_t = abs(min(x_offsets))
    max_t = abs(num_samples - abs(max(y_offsets)))  # Exclusive
#     print(min_t,max_t)
    print(np.array(data))
    for t in range(min_t, max_t):
       
        x_t = data[t + x_offsets, ...]
        y_t = data[t + y_offsets, ...]
        x.append(x_t)
        y.append(y_t)
    x = np.stack(x, axis=0)
    y = np.stack(y, axis=0)
    return x, y

In [147]:
time_ind = (df.index.values   - df.index.values.astype("datetime64[D]") )/ np.timedelta64(1, "D")
# print(np.tile(time_ind, [1, 207, 1]).transpose((2,1,0)))
print(np.tile(time_ind, [1, 207, 1]).transpose((2,1,0)).shape)

(1000, 207, 1)


In [154]:
list(x_offsets.shape)+[1]

[12, 1]

In [148]:
df.shape

(1000, 207)

In [149]:
x,y = generate_graph_seq2seq_io_data(df,x_offsets,y_offsets)

(1000, 207, 1)
[[[6.43750000e+01 0.00000000e+00]
  [6.76250000e+01 0.00000000e+00]
  [6.71250000e+01 0.00000000e+00]
  ...
  [5.92500000e+01 0.00000000e+00]
  [6.90000000e+01 0.00000000e+00]
  [6.18750000e+01 0.00000000e+00]]

 [[6.26666667e+01 3.47222222e-03]
  [6.85555556e+01 3.47222222e-03]
  [6.54444444e+01 3.47222222e-03]
  ...
  [5.58888889e+01 3.47222222e-03]
  [6.84444444e+01 3.47222222e-03]
  [6.28750000e+01 3.47222222e-03]]

 [[6.40000000e+01 6.94444444e-03]
  [6.37500000e+01 6.94444444e-03]
  [6.00000000e+01 6.94444444e-03]
  ...
  [6.13750000e+01 6.94444444e-03]
  [6.98571429e+01 6.94444444e-03]
  [6.20000000e+01 6.94444444e-03]]

 ...

 [[0.00000000e+00 4.61805556e-01]
  [6.84444444e+01 4.61805556e-01]
  [6.97777778e+01 4.61805556e-01]
  ...
  [6.35555556e+01 4.61805556e-01]
  [6.92222222e+01 4.61805556e-01]
  [5.26666667e+01 4.61805556e-01]]

 [[0.00000000e+00 4.65277778e-01]
  [6.71428571e+01 4.65277778e-01]
  [6.98571429e+01 4.65277778e-01]
  ...
  [6.41428571e+01 4.652

In [164]:
import pickle
import scipy.sparse as sp

In [165]:
def load_graph_data(pkl_filename):
    sensor_ids, sensor_id_to_ind, adj_mx = load_pickle(pkl_filename)
    return sensor_ids, sensor_id_to_ind, adj_mx


def load_pickle(pickle_file):
    try:
        with open(pickle_file, 'rb') as f:
            pickle_data = pickle.load(f)
    except UnicodeDecodeError as e:
        
        with open(pickle_file, 'rb') as f:
            pickle_data = pickle.load(f, encoding='latin1')
    except Exception as e:
        print('Unable to load data ', pickle_file, ':', e)
        raise
    return pickle_data


In [203]:
def calculate_random_walk_matrix(adj_mx):
    print(np.sum(adj_mx[0,:]))
    adj_mx = sp.coo_matrix(adj_mx)
    d = np.array(adj_mx.sum(1))
    print(d[0])
    d_inv = np.power(d, -1).flatten()
    d_inv[np.isinf(d_inv)] = 0.
    d_mat_inv = sp.diags(d_inv)
    random_walk_mx = d_mat_inv.dot(adj_mx).tocoo()
    return random_walk_mx

In [204]:
sensor_ids, sensor_id_to_ind, adj_mx = load_graph_data('/Users/icdi/Desktop/gpu-test/DCRNN/data/sensor_graph/adj_mx.pkl')
adj_mx.shape


(207, 207)

In [205]:
calculate_random_walk_matrix(adj_mx)

4.8790474
[4.8790474]


<207x207 sparse matrix of type '<class 'numpy.float32'>'
	with 1722 stored elements in COOrdinate format>

In [208]:
import tensorflow as tf
labels = tf.unstack(tf.reshape(np.random.random((10,12,10,1)), (10, 12, 10 * 1)), axis=1)

In [209]:
labels

[<tf.Tensor 'unstack:0' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:1' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:2' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:3' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:4' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:5' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:6' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:7' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:8' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:9' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:10' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:11' shape=(10, 10) dtype=float64>]

In [211]:
GO_SYMBOL = tf.zeros(shape=(10, 12 * 1))

In [212]:
labels.insert(0, GO_SYMBOL)

In [213]:
labels

[<tf.Tensor 'zeros:0' shape=(10, 12) dtype=float32>,
 <tf.Tensor 'unstack:0' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:1' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:2' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:3' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:4' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:5' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:6' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:7' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:8' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:9' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:10' shape=(10, 10) dtype=float64>,
 <tf.Tensor 'unstack:11' shape=(10, 10) dtype=float64>]